namespace ERP.Application.Products.DTOs;

public record ProductDto(
    Guid Id,
    string SaleCode,
    string? PurchaseCode,
    string ShortName,
    string Description,
    Guid LineId,
    Guid CategoryId,
    Guid SubcategoryId,
    Guid UnitOfMeasureId,
    Guid BrandId,
    Guid ProductTypeId,
    Guid TariffId,
    bool AppliesVatOnSale,
    Guid? SaleTaxId,
    bool AppliesVatOnPurchase,
    Guid? PurchaseTaxId,
    bool AppliesExciseTax,
    Guid? ExciseTaxId,
    bool IsService,
    bool TracksStock,
    bool IsActive,
    bool AvailableOnWeb,
    bool AvailableOnMobile,
    bool IsEcommerceActive,
    bool IsForSale,
    DateTime CreatedAt
);
