namespace ERP.Application.Products.DTOs;

public record ProductDto(
    Guid Id,
    string SaleCode,
    string? PurchaseCode,
    string ShortName,
    string Description,
    Guid LineId,
    Guid CategoryId,
    Guid SubcategoryId,
    string UomCode,
    Guid BrandId,
    Guid ProductTypeId,
    Guid TariffId,
    bool AppliesVatOnSale,
    string? SaleVatCode,
    bool AppliesVatOnPurchase,
    string? PurchaseVatCode,
    bool AppliesExciseTax,
    string? IceCode,
    bool IsService,
    bool TracksStock,
    bool IsActive,
    bool AvailableOnWeb,
    bool AvailableOnMobile,
    bool IsEcommerceActive,
    bool IsForSale,
    DateTime CreatedAt
);
