<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ZH.PrintAgent.Contracts\ZH.PrintAgent.Contracts.csproj" />
    <ProjectReference Include="..\ZH.PrintAgent.Core\ZH.PrintAgent.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
