# Bulk rename SaaS domain (run from repo root)
$ErrorActionPreference = 'Stop'
$root = Join-Path $PSScriptRoot '..'
$backend = Join-Path $root 'backend'

$excludePatterns = @('*Migrations\202*', '*ErpDbContextModelSnapshot.cs', '*.Designer.cs')

$files = Get-ChildItem $backend -Recurse -Filter '*.cs' | Where-Object {
    $p = $_.FullName
    -not ($excludePatterns | Where-Object { $p -like $_ })
}

$replacements = @(
    @('TenantSaasSubscriptionEvent', 'SubscriberSubscriptionEvent'),
    @('TenantSaasSubscription', 'SubscriberSubscription'),
    @('TenantSubscriptionFeatureOverride', 'SubscriptionFeatureOverride'),
    @('TenantSubscriptionUsage', 'SubscriptionUsage'),
    @('TenantSubscriptionStatus', 'SubscriptionStatus'),
    @('TenantSubscriptionCatalog', 'SubscriberSubscriptionCatalog'),
    @('TenantSubscriptionOverridesService', 'SubscriptionFeatureOverridesService'),
    @('ITenantSubscriptionOverridesService', 'ISubscriptionFeatureOverridesService'),
    @('TenantEntitlementsService', 'SubscriberEntitlementsService'),
    @('ITenantEntitlementsService', 'ISubscriberEntitlementsService'),
    @('TenantEntitlementsSnapshot', 'SubscriberEntitlementsSnapshot'),
    @('SaasFeatureDefinition', 'PlatformFeature'),
    @('SaasPlanFeature', 'CommercialPlanFeature'),
    @('SaasPlansAdminService', 'CommercialPlansAdminService'),
    @('SaasPlansBootstrap', 'CommercialPlansBootstrap'),
    @('SaasPlanCatalogDtos', 'CommercialPlanCatalogDtos'),
    @('SaasPlansAdminDtos', 'CommercialPlansAdminDtos'),
    @('SaasCatalogQuery', 'CommercialCatalogQuery'),
    @('ISaasPlansAdminService', 'ICommercialPlansAdminService'),
    @('ISaasCatalogQuery', 'ICommercialCatalogQuery'),
    @('SaasPlan', 'CommercialPlan'),
    @('SaasFeatureKind', 'PlatformFeatureKind'),
    @('SaasBillingCycle', 'CommercialBillingCycle'),
    @('TenantCustomMenu', 'SubscriberCustomMenu'),
    @('TenantMenuAdminService', 'SubscriberMenuAdminService'),
    @('ITenantMenuAdminService', 'ISubscriberMenuAdminService'),
    @('TenantMenuService', 'SubscriberMenuService'),
    @('TenantOnboardingService', 'SubscriberOnboardingService'),
    @('ITenantOnboardingService', 'ISubscriberOnboardingService'),
    @('TenantRepository', 'SubscriberRepository'),
    @('ITenantRepository', 'ISubscriberRepository'),
    @('TenantConfiguration', 'SubscriberConfiguration'),
    @('TenantCustomMenuConfiguration', 'SubscriberCustomMenuConfiguration'),
    @('SaasPlanConfiguration', 'CommercialPlanConfiguration'),
    @('SaasFeatureDefinitionConfiguration', 'PlatformFeatureConfiguration'),
    @('SaasPlanFeatureConfiguration', 'CommercialPlanFeatureConfiguration'),
    @('TenantSaasSubscriptionConfiguration', 'SubscriberSubscriptionConfiguration'),
    @('TenantSaasSubscriptionEventConfiguration', 'SubscriberSubscriptionEventConfiguration'),
    @('TenantSubscriptionFeatureOverrideConfiguration', 'SubscriptionFeatureOverrideConfiguration'),
    @('TenantSubscriptionUsageConfiguration', 'SubscriptionUsageConfiguration'),
    @('UpdateTenantSubscription', 'UpdateSubscriberSubscription'),
    @('UpdateTenantCompany', 'UpdateSubscriberCompany'),
    @('UpdateTenantOperationalSettings', 'UpdateSubscriberOperationalSettings'),
    @('UpdateTenantGlobalParameters', 'UpdateSubscriberGlobalParameters'),
    @('UpdateTenantPasswordResetMode', 'UpdateSubscriberPasswordResetMode'),
    @('CreateTenant', 'CreateSubscriber'),
    @('SuperAdminTenant', 'SuperAdminSubscriber'),
    @('GetSuperAdminTenants', 'GetSuperAdminSubscribers'),
    @('SuperAdminCreateTenant', 'SuperAdminCreateSubscriber'),
    @('RegisterTenantWithAdmin', 'RegisterSubscriberWithAdmin'),
    @('TenantsController', 'SubscribersController'),
    @('SaasPlansAdminController', 'CommercialPlansAdminController'),
    @('SaasEntitlementsController', 'SubscriberEntitlementsController'),
    @('TenantDto', 'SubscriberDto'),
    @('TenantPublicSettingsDto', 'SubscriberPublicSettingsDto'),
    @('TenantSubscriptionTests', 'SubscriberSubscriptionTests'),
    @('ERP.Domain.Modules.Tenants', 'ERP.Domain.Modules.Subscribers'),
    @('ERP.Application.Modules.Tenants', 'ERP.Application.Modules.Subscribers'),
    @('tenant_saas_subscription_events', 'subscriber_subscription_events'),
    @('tenant_saas_subscriptions', 'subscriber_subscriptions'),
    @('tenant_subscription_feature_overrides', 'subscription_feature_overrides'),
    @('tenant_subscription_usages', 'subscription_usages'),
    @('tenant_custom_menus', 'subscriber_custom_menus'),
    @('saas_feature_definitions', 'platform_features'),
    @('saas_plans', 'commercial_plans'),
    @('saas_plan_features', 'commercial_plan_features'),
    @('ux_tenant_saas_subscriptions_tenant', 'ux_subscriber_subscriptions_subscriber'),
    @('ix_tenant_saas_subscription_events_tenant_occurred', 'ix_subscriber_subscription_events_subscriber_occurred'),
    @('ux_tenant_subscription_usages_period', 'ux_subscription_usages_period'),
    @('ux_tenant_sub_feat_override_sub_feature', 'ux_subscription_feature_override_sub_feature'),
    @('ix_tenants_slug', 'ix_subscribers_slug'),
    @('ux_saas_feature_definitions_code', 'ux_platform_features_code'),
    @('ux_saas_plans_code', 'ux_commercial_plans_code'),
    @('ux_saas_plan_features_plan_feature', 'ux_commercial_plan_features_plan_feature'),
    @('api/superadmin/saas-plans', 'api/superadmin/commercial-plans'),
    @('api/saas/entitlements', 'api/subscribers/entitlements'),
    @('SyncTenantSubscriptionsFromPlanCodeAsync', 'SyncSubscriberSubscriptionsFromPlanCodeAsync'),
    @('MaxActiveTenants', 'MaxActiveSubscribers'),
    @('GetBlockingReasonIfAtActiveTenantCapAsync', 'GetBlockingReasonIfAtActiveSubscriberCapAsync'),
    @('tenant-demo', 'subscriber-demo'),
    @('HasColumnName("tenant_id")', 'HasColumnName("subscriber_id")'),
    @('.HasColumnName("tenant_id")', '.HasColumnName("subscriber_id")'),
    @('Memberships', 'CompanyUserMemberships'),
    @('Membership', 'CompanyUserMembership'),
    @('memberships', 'company_user_memberships'),
    @('ICurrentTenant', 'ICurrentSubscriber'),
    @('CurrentTenantService', 'CurrentSubscriberService'),
    @('CurrentTenant', 'CurrentSubscriber'),
    @('JobTenantContext', 'JobSubscriberContext'),
    @('ITenantEntity', 'ISubscriberScopedEntity'),
    @('TenantId', 'SubscriberId'),
    @('tenant_id', 'subscriber_id'),
    @('tenant_ids', 'subscriber_ids'),
    @('tenantId', 'subscriberId'),
    @('TenantIds', 'SubscriberIds'),
    @('SwitchTenant', 'SwitchSubscriber'),
    @('switch-tenant', 'switch-subscriber'),
    @('select-tenant', 'select-subscriber'),
    @('superadmin/tenants', 'superadmin/subscribers'),
    @('api/tenants', 'api/subscribers'),
    @('TenantSelect', 'SubscriberSelect'),
    @('TenantAccess', 'SubscriberAccess'),
    @('TenantFeature', 'SubscriberFeature'),
    @('tenantAccess', 'subscriberAccess'),
    @('tenantSlug', 'subscriberSlug'),
    @('TenantSlug', 'SubscriberSlug'),
    @('TenantName', 'SubscriberName'),
    @('tenantName', 'subscriberName'),
    @('GLOBAL_TENANT_ID', 'GLOBAL_SUBSCRIBER_ID'),
    @('tenantIds', 'subscriberIds'),
    @('SuperAdminTenants', 'SuperAdminSubscribers'),
    @('SuperAdminTenantHandlers', 'SuperAdminSubscriberHandlers'),
    @('SuperAdminTenantCommands', 'SuperAdminSubscriberCommands'),
    @('TenantMembership', 'SubscriberMembership'),
    @('TenantAccessPage', 'SubscriberAccessPage'),
    @('companiesTenantDetailNav', 'companiesSubscriberDetailNav'),
    @('ZHAppTenantHeader', 'ZHAppSubscriberHeader'),
    @('impersonation-tenant', 'impersonation-subscriber'),
    @('SaasPlanLayout', 'CommercialPlanLayout'),
    @('Tenant ', 'Subscriber '),
    @('Tenant)', 'Subscriber)'),
    @('Tenant,', 'Subscriber,'),
    @('Tenant.', 'Subscriber.'),
    @('Tenant;', 'Subscriber;'),
    @('<Tenant>', '<Subscriber>'),
    @('(Tenant ', '(Subscriber '),
    @('Tenant>', 'Subscriber>'),
    @('DbSet<Tenant>', 'DbSet<Subscriber>'),
    @('typeof(Tenant)', 'typeof(Subscriber)'),
    @('class Tenant', 'class Subscriber'),
    @('sealed class Tenant', 'sealed class Subscriber'),
    @('public class Tenant', 'public class Subscriber'),
    @('tenants', 'subscribers')
)

$count = 0
foreach ($file in $files) {
    $content = [System.IO.File]::ReadAllText($file.FullName)
    $original = $content
    foreach ($r in $replacements) {
        $content = $content.Replace($r[0], $r[1])
    }
    if ($content -ne $original) {
        [System.IO.File]::WriteAllText($file.FullName, $content)
        $count++
    }
}
Write-Host "Updated $count files"
